### ISSUE TITLE
MFA requirement breaks m365 login

### ISSUE THREAD

**Issue by preavy** [Voitanos/azure-pipelines-spfx-templates#22]
I set up a new tenant today Microsoft 365 Developer Program and if I understand it correctly, all accounts seem to require MFA set up on them after 14 days.

`m365 login` with username and password doesn't support MFA and I wondered if you had any recommendation from the other `m365 login` authentication options e.g. cert, app registration, managed identity etc.

**Comment by andrewconnell** [comment]
Not at this time... unless something changed, you can't deploy apps via apps or MSI's *yet*. I've seen where someone wrote a blog post about using certs, but I've yet to see it work.

AFAIK, using a service account without MFA enabled is the only option today.

**Comment by preavy** [comment]
Thanks, Andrew
