### ISSUE TITLE
Show test results and coverage when tests fail

### ISSUE THREAD

**Issue by Leif-Frederiksen** [Voitanos/azure-pipelines-spfx-templates#4]
Even when one or more tests are failing, it is relevant to see the outcome of the test - maybe even more so, than when everything is just Hunky-dory.
Some sort of "continue-on-error" on the "run tests" action maybe.

**Comment by andrewconnell** [comment]
Understanding the use case, but here's the problem I'm not sure how you overcome:

You can set a job to have the ability to not fail when there's an error (`continueOnError`), but the problem with this is a failed job, when running tests, means the tests failed but you won't treat it as such. 

IOW, you get the reporting you are asking for, but the point of the job is to ensure tests are passing because if they don't, they should block the deployment. If the tests failed, the priority isn't to look at code coverage or test results, rather the priority is to fix the failed tests locally, then re-push your changes that trigger the CI build.

From my POV, I don't think this is something you want to do... you can still see the outcome of the test by looking at the log of the task run step which will explicitly write out the results of the failed test, so you'll still have that, it just won't be in the pretty report that's published to the pipeline run instance. 

Therefore, I'm not inclined to add this feature...

**Comment by Leif-Frederiksen** [comment]
I get your point - on one hand the reporting part should continue after a failed test, but onwards from there nothing more should happen, ie. no deployment.
I have a GUI based setup that accomplishes just that - by setting the "Continue on error" on the "execute tests" step, and setting the "Fail if there are test failures" on the "Pubish Test Results" step. See attached screenshots. 
I fully respect your decisions regarding this - but it would be super cool to have it implemented :-)

Regards
Leif
![execute test_continueonerror](https://user-images.githubusercontent.com/25172917/65574035-9c1b2f00-df6c-11e9-9458-251ba9739eb3.png)
![publishtestresults_failiftherearetestfailures](https://user-images.githubusercontent.com/25172917/65574036-9c1b2f00-df6c-11e9-8a4c-cfe8b2584874.png)

**Comment by andrewconnell** [comment]
Do you know offhand what property that is on that task? Not the GUI representation, but the YAML one?

Regardless, feel free to submit a PR if you can prove that this will satisfy both situations. My only "line in the sand" is making sure that the entire test job is considered a FAIL if a test doesn't pass.

**Comment by Leif-Frederiksen** [comment]
The YAML property is "failTaskOnFailedTests". Below is a YAML export/view
from my setup:

steps: - task: PublishTestResults@2 displayName: 'Publish Test Results
$(System.DefaultWorkingDirectory)/junit.xml' inputs: testResultsFiles:
'$(System.DefaultWorkingDirectory)/junit.xml' *failTaskOnFailedTests: true*

Regards
Leif

Den ons. 25. sep. 2019 kl. 14.14 skrev Andrew Connell <
notifications@github.com>:

**Comment by andrewconnell** [comment]
Interesting... care to submit a PR? Hard to read your comment as line wrapping looks all messed up...

**Comment by Leif-Frederiksen** [comment]
Sure, I will look into that. Do I just create a feature branch and make the
PR from that?

Regards
Leif

Den man. 30. sep. 2019 kl. 12.55 skrev Andrew Connell <
notifications@github.com>:

**Comment by andrewconnell** [comment]
All that's necessary is to fork, make your edits and submit a PR. What most do is create a branch with just your edits in your fork and submit the PR from that.

**Comment by Leif-Frederiksen** [comment]
Hi again,

I created a PR now. I hope I did it right - it's kinda my first attempt at
this stuff ;-)

/Leif

Den ons. 2. okt. 2019 kl. 15.50 skrev Andrew Connell <
notifications@github.com>:

**Comment by andrewconnell** [comment]
Cool... I see it. I'll take a look when I have some spare cycles. Thanks!

**Comment by andrewconnell** [comment]
This was merged in v1.0.1. Shows closed because I squashed your commits into a single one.

**Comment by Leif-Frederiksen** [comment]
Hi Andrew,

It seems like the changes to sample/azure-pipelines.yml (
https://github.com/Leif-Frederiksen/azure-pipelines-spfx-templates/commit/3b941504cddec06da9c564d5e60a24c360326da9)
was not merged back in with the pull request.

I believe they go hand in hand with the changes to the jobs, so to get full
effect from running the sample, I think they should be included as well.

Or am I missing something?

Regards
Leif

Den man. 14. okt. 2019 kl. 22.42 skrev Andrew Connell <
notifications@github.com>:

**Comment by andrewconnell** [comment]
Correct... they weren't. You had changed it so the **Test** stage required **Build** to complete. I intentionally didn't want that to show they could run in parallel. From my test, [it seemed to work as intended](https://dev.azure.com/aconn/Azure%20Pipelines%20SPFx%20Templates/_build/results?buildId=679&view=results). You disagree?

**Comment by Leif-Frederiksen** [comment]
Ah, yes I see - that seems to be correct in order to get the parallelity.

Regards
Leif

Den tir. 15. okt. 2019 kl. 13.11 skrev Andrew Connell <
notifications@github.com>:
